---
- hosts: localhost
  connection: local

  vars_files:
    - vars/config.yml
    - vars/homebrew-cask-apps.yml
    - vars/homebrew-packages.yml
    - vars/mas-apps.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
      ignore_errors: yes
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
    # - role: geerlingguy.dotfiles
    #   when: configure_dotfiles
    #   tags: ['dotfiles']      

  tasks:
    - include: tasks/oh-my-zsh-setup.yml
      tags: ['zsh']
